inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-lts: rubocop-lts.yml

require:
  - 'rubocop-performance'
  - 'rubocop-rake'
  - 'rubocop-rspec'
  - 'rubocop-thread_safety'

AllCops:
  DisplayCopNames: true # Display the name of the failing cops

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120
